/**
 * Blog HTML Importer
 *
 * Parses a complete HTML document (or fragment) — typically generated by
 * ChatGPT, Claude, Gemini, or another AI — and extracts every field the
 * AIBlaze blog CMS cares about: title, slug, excerpt, body, SEO metadata,
 * featured image, FAQs, content stats, and category/tag suggestions.
 *
 * Browser-only: relies on DOMParser. Used from the admin UI.
 */
import { sanitizeHtml, addHeadingIds, htmlStats } from "./html-sanitize";
import { catalog } from "@/data/catalog";

export interface ImportedFaq { q: string; a: string }

export interface ImportedHeading { level: number; text: string; id: string }

export interface ImportStats {
  words: number;
  readingTime: number;
  headings: number;
  paragraphs: number;
  images: number;
  tables: number;
  codeBlocks: number;
  blockquotes: number;
  lists: number;
  h1: number; h2: number; h3: number; h4: number;
}

export interface ImportWarning {
  level: "error" | "warning" | "info";
  message: string;
  fixKey?: string; // hint for one-click fix UI
}

export interface ImportedBlog {
  // Basic
  title: string;
  slug: string;
  excerpt: string;
  content_html: string;       // sanitized
  published_at?: string;
  // Media
  cover_url?: string;
  cover_alt?: string;
  // SEO
  seo_title: string;
  seo_description: string;
  focus_keyword: string;
  secondary_keywords: string[];
  canonical_url?: string;
  og_title: string;
  og_description: string;
  og_image?: string;
  twitter_title: string;
  twitter_description: string;
  twitter_image?: string;
  // Taxonomy suggestions
  tags: string[];
  category_suggestion?: { slug: string; name: string };
  subcategory_suggestion?: { slug: string; name: string };
  related_tools: string[];
  // Structured
  headings: ImportedHeading[];
  faqs: ImportedFaq[];
  // Diagnostics
  stats: ImportStats;
  warnings: ImportWarning[];
  scores: {
    seo: number;
    readability: number;
    headingStructure: number;
    internalLinking: number;
    completeness: number;
  };
}

// ---------- helpers ----------

const STOP_WORDS = new Set([
  "the","a","an","and","or","but","of","to","in","on","for","with","is","are",
  "was","were","be","been","by","at","as","it","this","that","these","those",
  "from","you","your","we","our","they","their","i","me","my","he","she","his",
  "her","its","not","no","do","does","did","will","would","can","could","should",
  "have","has","had","just","than","then","so","too","very","also","more","most",
  "into","about","over","under","up","down","out","one","two","new","get","use",
  "using","like","what","when","why","how","which","who","best","top","guide",
]);

export function slugify(input: string): string {
  return (input || "")
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 80);
}

function clamp(s: string, min: number, max: number): string {
  const t = (s || "").trim().replace(/\s+/g, " ");
  if (t.length <= max) return t;
  const cut = t.slice(0, max);
  const sp = cut.lastIndexOf(" ");
  return (sp > min ? cut.slice(0, sp) : cut).replace(/[,;:.\s]+$/, "") + "…";
}

function textOf(el: Element | null | undefined): string {
  return (el?.textContent ?? "").replace(/\s+/g, " ").trim();
}

function getMeta(doc: Document, names: string[]): string | undefined {
  for (const n of names) {
    const el =
      doc.querySelector(`meta[name="${n}"]`) ||
      doc.querySelector(`meta[property="${n}"]`);
    const v = el?.getAttribute("content")?.trim();
    if (v) return v;
  }
  return undefined;
}

function repairMalformedHtml(raw: string): string {
  return raw.replace(
    /<script\b([^>]*)type=["']application\/ld\+json["']([^>]*)>([\s\S]*?)(?=\n\s*(?:[A-Z][^<\n]{20,}|<\/head>|<body\b|$))/gi,
    (match, before, after, body) => {
      if (/<\/script\s*>/i.test(match)) return match;
      const end = Math.max(body.lastIndexOf("}"), body.lastIndexOf("]"));
      if (end === -1) return "";
      return `<script${before}type="application/ld+json"${after}>${body.slice(0, end + 1)}</script>\n${body.slice(end + 1)}`;
    },
  );
}

// ---------- core parser ----------

export function parseBlogHtml(raw: string): ImportedBlog {
  const input = repairMalformedHtml(raw || "").trim();
  if (!input) return emptyResult();

  // Wrap fragments so DOMParser builds a usable tree.
  const looksLikeDocument = /<html[\s>]/i.test(input) || /<!doctype/i.test(input);
  const source = looksLikeDocument ? input : `<!doctype html><html><head></head><body>${input}</body></html>`;
  const doc = new DOMParser().parseFromString(source, "text/html");

  // Strip noise we never want in the article body.
  doc
    .querySelectorAll("script, style, noscript, nav, header > nav, footer, aside, form, .ads, .ad, [aria-hidden=true]")
    .forEach((n) => n.remove());

  // Pick the main article container.
  const articleEl =
    doc.querySelector("article") ||
    doc.querySelector("main") ||
    doc.querySelector('[role="main"]') ||
    doc.body;

  // Title
  const h1 = articleEl.querySelector("h1");
  const titleTag = textOf(doc.querySelector("title"));
  const ogTitleMeta = getMeta(doc, ["og:title", "twitter:title"]);
  const title = textOf(h1) || ogTitleMeta || titleTag || "Untitled";

  // Cover image — first image inside article or og:image
  const ogImage = getMeta(doc, ["og:image", "twitter:image"]);
  const firstImg = articleEl.querySelector("img");
  const cover_url = ogImage || firstImg?.getAttribute("src") || undefined;
  const cover_alt =
    firstImg?.getAttribute("alt")?.trim() ||
    (cover_url ? `${title} cover image` : undefined);

  // Remove the h1 from body so we don't render the title twice.
  if (h1) h1.remove();
  // Remove the cover image from the body if it'll be promoted to a hero.
  if (firstImg && cover_url && firstImg.getAttribute("src") === cover_url) {
    firstImg.closest("figure")?.remove() ?? firstImg.remove();
  }

  // Headings list
  const headings: ImportedHeading[] = Array.from(articleEl.querySelectorAll("h2, h3, h4")).map(
    (h) => {
      const text = textOf(h);
      return { level: Number(h.tagName.substring(1)), text, id: slugify(text) };
    },
  );

  // FAQ detection — h2/h3 followed by a paragraph, plus questions ending in "?"
  const faqs = extractFaqs(articleEl);

  // First meaningful paragraph for excerpt fallback
  const firstParaText = (() => {
    for (const p of Array.from(articleEl.querySelectorAll("p"))) {
      const t = textOf(p);
      if (t.length >= 40) return t;
    }
    return textOf(articleEl).slice(0, 320);
  })();

  // Meta extraction
  const metaDescription = getMeta(doc, ["description", "og:description", "twitter:description"]);
  const metaKeywords = (getMeta(doc, ["keywords"]) || "")
    .split(",").map((s) => s.trim()).filter(Boolean);
  const canonical = doc.querySelector('link[rel="canonical"]')?.getAttribute("href") || undefined;

  // Sanitize + add heading ids on the cleaned body
  const bodyHtml = articleEl.innerHTML;
  const content_html = addHeadingIds(sanitizeHtml(bodyHtml));

  // Stats (use raw cleaned html so non-sanitized stats match render output closely)
  const baseStats = htmlStats(content_html);
  const stats: ImportStats = {
    ...baseStats,
    paragraphs: (content_html.match(/<p[\s>]/g) ?? []).length,
    codeBlocks: (content_html.match(/<pre[\s>]/g) ?? []).length,
    blockquotes: (content_html.match(/<blockquote[\s>]/g) ?? []).length,
    lists: (content_html.match(/<(ul|ol)[\s>]/g) ?? []).length,
    h1: 0,
    h2: (content_html.match(/<h2[\s>]/g) ?? []).length,
    h3: (content_html.match(/<h3[\s>]/g) ?? []).length,
    h4: (content_html.match(/<h4[\s>]/g) ?? []).length,
  };

  // Keyword extraction
  const fullText = (title + " " + firstParaText + " " + headings.map((h) => h.text).join(" ")).toLowerCase();
  const keywords = topKeywords(fullText, 8);
  const focus_keyword = metaKeywords[0] || keywords[0] || "";
  const secondary_keywords = (metaKeywords.length > 1 ? metaKeywords.slice(1) : keywords.slice(1, 6));

  // Category / subcategory / tool suggestions
  const corpus = (title + " " + textOf(articleEl)).toLowerCase();
  const taxonomy = suggestTaxonomy(corpus);

  // Final fields, with intelligent fallbacks + SEO clamping
  const excerpt = clamp(metaDescription || firstParaText, 110, 200);
  const seo_title = clamp(ogTitleMeta || title, 40, 60);
  const seo_description = clamp(metaDescription || firstParaText, 140, 160);
  const og_title = clamp(ogTitleMeta || title, 40, 70);
  const og_description = clamp(metaDescription || firstParaText, 140, 200);
  const tw_title = clamp(ogTitleMeta || title, 40, 70);
  const tw_description = clamp(metaDescription || firstParaText, 140, 200);

  const result: ImportedBlog = {
    title,
    slug: slugify(title),
    excerpt,
    content_html,
    cover_url,
    cover_alt,
    seo_title,
    seo_description,
    focus_keyword,
    secondary_keywords,
    canonical_url: canonical,
    og_title,
    og_description,
    og_image: cover_url,
    twitter_title: tw_title,
    twitter_description: tw_description,
    twitter_image: cover_url,
    tags: Array.from(new Set([...(metaKeywords.slice(0, 6)), ...keywords.slice(0, 6)])).slice(0, 8),
    category_suggestion: taxonomy.category,
    subcategory_suggestion: taxonomy.subcategory,
    related_tools: taxonomy.tools,
    headings,
    faqs,
    stats,
    warnings: [],
    scores: { seo: 0, readability: 0, headingStructure: 0, internalLinking: 0, completeness: 0 },
  };

  result.warnings = validate(result, articleEl);
  result.scores = score(result);
  return result;
}

// ---------- FAQ extraction ----------

function extractFaqs(root: Element): ImportedFaq[] {
  const out: ImportedFaq[] = [];

  // Pattern A: <details><summary>Q</summary>A</details>
  root.querySelectorAll("details").forEach((d) => {
    const q = textOf(d.querySelector("summary"));
    const a = textOf(d).replace(q, "").trim();
    if (q && a) out.push({ q, a });
  });

  // Pattern B: question-style headings followed by paragraphs/lists
  const hs = Array.from(root.querySelectorAll("h2, h3, h4"));
  for (const h of hs) {
    const q = textOf(h);
    if (!/\?\s*$/.test(q)) continue;
    const parts: string[] = [];
    let sib = h.nextElementSibling;
    while (sib && !/^H[1-6]$/.test(sib.tagName)) {
      const t = textOf(sib);
      if (t) parts.push(t);
      sib = sib.nextElementSibling;
    }
    const a = parts.join(" ").trim();
    if (a) out.push({ q, a });
  }

  // De-dupe by question
  const seen = new Set<string>();
  return out.filter((f) => (seen.has(f.q) ? false : (seen.add(f.q), true)));
}

// ---------- keyword + taxonomy ----------

function topKeywords(text: string, limit: number): string[] {
  const freq = new Map<string, number>();
  const tokens = text
    .replace(/[^a-z0-9\s-]/g, " ")
    .split(/\s+/)
    .filter((w) => w.length >= 3 && !STOP_WORDS.has(w));
  for (const w of tokens) freq.set(w, (freq.get(w) || 0) + 1);
  // Bigrams
  for (let i = 0; i < tokens.length - 1; i++) {
    const bg = tokens[i] + " " + tokens[i + 1];
    if (STOP_WORDS.has(tokens[i]) || STOP_WORDS.has(tokens[i + 1])) continue;
    freq.set(bg, (freq.get(bg) || 0) + 2); // bias toward phrases
  }
  return Array.from(freq.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, limit * 2)
    .map(([w]) => w)
    .filter((w, _, arr) => !arr.some((o) => o !== w && o.includes(w + " ") || o.includes(" " + w)))
    .slice(0, limit);
}

function suggestTaxonomy(corpus: string): {
  category?: { slug: string; name: string };
  subcategory?: { slug: string; name: string };
  tools: string[];
} {
  let bestCat: { slug: string; name: string; score: number } | undefined;
  let bestSub: { slug: string; name: string; score: number } | undefined;
  const tools = new Set<string>();

  for (const cat of catalog) {
    const catHits = countOccurrences(corpus, cat.name.toLowerCase());
    if (catHits && (!bestCat || catHits > bestCat.score)) {
      bestCat = { slug: cat.slug, name: cat.name, score: catHits };
    }
    for (const sub of cat.subs) {
      const subHits = countOccurrences(corpus, sub.name.toLowerCase());
      if (subHits && (!bestSub || subHits > bestSub.score)) {
        bestSub = { slug: sub.slug, name: sub.name, score: subHits };
      }
      for (const t of sub.tools) {
        if (countOccurrences(corpus, t.name.toLowerCase()) > 0) tools.add(t.name);
      }
    }
  }
  return {
    category: bestCat && { slug: bestCat.slug, name: bestCat.name },
    subcategory: bestSub && { slug: bestSub.slug, name: bestSub.name },
    tools: Array.from(tools).slice(0, 8),
  };
}

function countOccurrences(haystack: string, needle: string): number {
  if (!needle || needle.length < 3) return 0;
  const re = new RegExp(`\\b${needle.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "g");
  return (haystack.match(re) ?? []).length;
}

// ---------- validation + scoring ----------

function validate(r: ImportedBlog, root: Element): ImportWarning[] {
  const w: ImportWarning[] = [];
  if (!r.title || r.title === "Untitled") w.push({ level: "error", message: "Missing H1 / title.", fixKey: "title" });
  if (!r.seo_description) w.push({ level: "error", message: "Missing meta description.", fixKey: "seo_description" });
  if (!r.seo_title) w.push({ level: "warning", message: "Missing SEO title — using H1.", fixKey: "seo_title" });
  if (!r.cover_url) w.push({ level: "warning", message: "No featured image detected.", fixKey: "cover_url" });

  const imgs = root.querySelectorAll("img");
  const missingAlt = Array.from(imgs).filter((i) => !i.getAttribute("alt")?.trim()).length;
  if (missingAlt > 0) w.push({ level: "warning", message: `${missingAlt} image(s) missing ALT text.`, fixKey: "img_alt" });

  if ((r.content_html.match(/<a\b[^>]*href=/g) ?? []).length === 0) {
    w.push({ level: "info", message: "No links detected — internal linking engine will run at render time." });
  }

  // Duplicate headings
  const seen = new Map<string, number>();
  for (const h of r.headings) seen.set(h.text, (seen.get(h.text) || 0) + 1);
  for (const [t, c] of seen) if (c > 1) w.push({ level: "warning", message: `Duplicate heading: "${t}" (${c}×)` });

  // Hierarchy: H3 without preceding H2, H4 without H3
  let lastH = 1;
  for (const h of r.headings) {
    if (h.level > lastH + 1) w.push({ level: "warning", message: `Heading jumps from H${lastH} to H${h.level}: "${h.text}"` });
    lastH = h.level;
  }

  if (r.stats.words < 300) w.push({ level: "warning", message: `Thin content: only ${r.stats.words} words (aim for 600+).` });

  return w;
}

function score(r: ImportedBlog): ImportedBlog["scores"] {
  // SEO score
  let seo = 100;
  if (!r.title) seo -= 25;
  if (!r.seo_title || r.seo_title.length < 30) seo -= 10;
  if (!r.seo_description || r.seo_description.length < 120) seo -= 15;
  if (!r.cover_url) seo -= 10;
  if (!r.focus_keyword) seo -= 10;
  if (r.stats.images === 0) seo -= 5;
  if (r.stats.words < 600) seo -= 15;

  // Readability (Flesch-ish, but quick: based on avg sentence and word length)
  const text = r.content_html.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
  const sentences = Math.max(1, (text.match(/[.!?]+/g) ?? []).length);
  const avgSentence = r.stats.words / sentences;
  const readability = clampNum(110 - avgSentence * 2.5, 0, 100);

  // Heading structure
  let headingScore = 60;
  if (r.stats.h2 >= 3) headingScore += 20;
  if (r.stats.h3 >= 2) headingScore += 10;
  if (r.stats.h2 > 0 && r.stats.h3 >= 0) headingScore += 10;
  headingScore = clampNum(headingScore, 0, 100);

  // Internal linking — measured at render time; baseline from raw count
  const linkCount = (r.content_html.match(/<a\b[^>]*href=/g) ?? []).length;
  const internal = clampNum(40 + linkCount * 8, 0, 100);

  // Completeness
  let complete = 40;
  if (r.cover_url) complete += 10;
  if (r.faqs.length) complete += 15;
  if (r.stats.images >= 2) complete += 10;
  if (r.tags.length >= 3) complete += 10;
  if (r.stats.words >= 800) complete += 15;
  complete = clampNum(complete, 0, 100);

  return {
    seo: clampNum(seo, 0, 100),
    readability: Math.round(readability),
    headingStructure: headingScore,
    internalLinking: internal,
    completeness: complete,
  };
}

function clampNum(n: number, min: number, max: number) {
  return Math.max(min, Math.min(max, Math.round(n)));
}

function emptyResult(): ImportedBlog {
  return {
    title: "", slug: "", excerpt: "", content_html: "",
    seo_title: "", seo_description: "", focus_keyword: "", secondary_keywords: [],
    og_title: "", og_description: "", twitter_title: "", twitter_description: "",
    tags: [], related_tools: [], headings: [], faqs: [],
    stats: { words: 0, readingTime: 0, headings: 0, paragraphs: 0, images: 0, tables: 0, codeBlocks: 0, blockquotes: 0, lists: 0, h1: 0, h2: 0, h3: 0, h4: 0 },
    warnings: [{ level: "error", message: "No HTML provided." }],
    scores: { seo: 0, readability: 0, headingStructure: 0, internalLinking: 0, completeness: 0 },
  };
}

/**
 * Map an ImportedBlog into the CrudPage field shape used by the blog admin.
 * Only includes fields that have meaningful values so we don't overwrite
 * existing data with empty strings.
 */
export function toBlogFormPatch(r: ImportedBlog): Record<string, unknown> {
  const patch: Record<string, unknown> = {};
  const setIf = (k: string, v: unknown) => {
    if (v === undefined || v === null) return;
    if (typeof v === "string" && !v.trim()) return;
    if (Array.isArray(v) && v.length === 0) return;
    patch[k] = v;
  };
  setIf("title", r.title);
  setIf("slug", r.slug);
  setIf("excerpt", r.excerpt);
  setIf("content_html", r.content_html);
  setIf("cover_url", r.cover_url);
  setIf("tags", r.tags);
  setIf("seo_title", r.seo_title);
  setIf("seo_description", r.seo_description);
  setIf("focus_keyword", r.focus_keyword);
  setIf("canonical_url", r.canonical_url);
  setIf("og_title", r.og_title);
  setIf("og_description", r.og_description);
  setIf("og_image", r.og_image);
  setIf("twitter_title", r.twitter_title);
  setIf("twitter_description", r.twitter_description);
  setIf("twitter_image", r.twitter_image);
  return patch;
}
