import { createFileRoute } from "@tanstack/react-router";
import { LegalPage } from "@/components/LegalPage";

export const Route = createFileRoute("/disclaimer")({
  head: () => ({
    meta: [
      { title: "Disclaimer — AI Blaze" },
      { name: "description", content: "Editorial, affiliate, and AI-content disclaimers for AI Blaze. Information accuracy and third-party tool disclaimers." },
      { name: "keywords", content: "disclaimer, affiliate disclosure, AI content disclaimer, AI Blaze" },
      { property: "og:title", content: "Disclaimer — AI Blaze" },
      { property: "og:description", content: "Editorial and affiliate disclaimers." },
      { property: "og:url", content: "https://aiblaze.io/disclaimer" },
    ],
    links: [{ rel: "canonical", href: "https://aiblaze.io/disclaimer" }],
  }),
  component: () => (
    <LegalPage title="Disclaimer" updated="June 4, 2026">
      <h2>Editorial accuracy</h2>
      <p>AI Blaze curates information about third-party AI tools. We strive for accuracy, but features, pricing, and availability change frequently. Always verify on the tool's own website before making decisions.</p>

      <h2>No professional advice</h2>
      <p>Content on AI Blaze is for informational and educational purposes only and does not constitute professional, legal, medical, financial, or investment advice.</p>

      <h2>AI-generated content</h2>
      <p>Some content on AI Blaze may be assisted or generated by AI. We review such content but cannot guarantee perfect accuracy. Treat AI-assisted content as a starting point, not a final source of truth.</p>

      <h2>Affiliate disclosure</h2>
      <p>Some outbound links may be affiliate links. If you sign up via these links, we may earn a small commission at no additional cost to you. This does not influence our editorial rankings or recommendations.</p>

      <h2>Third-party trademarks</h2>
      <p>All third-party trademarks, product names, and logos are the property of their respective owners. Their use on AI Blaze does not imply endorsement.</p>

      <h2>Contact</h2>
      <p><a href="mailto:aiblaze.io@gmail.com">aiblaze.io@gmail.com</a></p>
    </LegalPage>
  ),
});
