/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolSlugRouteImport } from './routes/tool.$slug'
import { Route as LearnSwipeRouteImport } from './routes/learn.swipe'
import { Route as LearnSpinRouteImport } from './routes/learn.spin'
import { Route as LearnScratchRouteImport } from './routes/learn.scratch'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as CategorySlugIndexRouteImport } from './routes/category.$slug.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as LearnTaskIdRouteImport } from './routes/learn.task.$id'
import { Route as CategorySlugSubRouteImport } from './routes/category.$slug.$sub'
import { Route as AdminAdminToolsRouteImport } from './routes/_admin.admin.tools'
import { Route as AdminAdminPromptsRouteImport } from './routes/_admin.admin.prompts'
import { Route as AdminAdminLearnTasksRouteImport } from './routes/_admin.admin.learn-tasks'
import { Route as HowtoCategorySubToolRouteImport } from './routes/howto.$category.$sub.$tool'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolSlugRoute = ToolSlugRouteImport.update({
  id: '/tool/$slug',
  path: '/tool/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSwipeRoute = LearnSwipeRouteImport.update({
  id: '/learn/swipe',
  path: '/learn/swipe',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSpinRoute = LearnSpinRouteImport.update({
  id: '/learn/spin',
  path: '/learn/spin',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnScratchRoute = LearnScratchRouteImport.update({
  id: '/learn/scratch',
  path: '/learn/scratch',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugIndexRoute = CategorySlugIndexRouteImport.update({
  id: '/category/$slug/',
  path: '/category/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const LearnTaskIdRoute = LearnTaskIdRouteImport.update({
  id: '/learn/task/$id',
  path: '/learn/task/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugSubRoute = CategorySlugSubRouteImport.update({
  id: '/category/$slug/$sub',
  path: '/category/$slug/$sub',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminToolsRoute = AdminAdminToolsRouteImport.update({
  id: '/admin/tools',
  path: '/admin/tools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPromptsRoute = AdminAdminPromptsRouteImport.update({
  id: '/admin/prompts',
  path: '/admin/prompts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminLearnTasksRoute = AdminAdminLearnTasksRouteImport.update({
  id: '/admin/learn-tasks',
  path: '/admin/learn-tasks',
  getParentRoute: () => AdminRoute,
} as any)
const HowtoCategorySubToolRoute = HowtoCategorySubToolRouteImport.update({
  id: '/howto/$category/$sub/$tool',
  path: '/howto/$category/$sub/$tool',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/prompts': typeof PromptsRoute
  '/ranking': typeof RankingRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/learn/scratch': typeof LearnScratchRoute
  '/learn/spin': typeof LearnSpinRoute
  '/learn/swipe': typeof LearnSwipeRoute
  '/tool/$slug': typeof ToolSlugRoute
  '/admin/learn-tasks': typeof AdminAdminLearnTasksRoute
  '/admin/prompts': typeof AdminAdminPromptsRoute
  '/admin/tools': typeof AdminAdminToolsRoute
  '/category/$slug/$sub': typeof CategorySlugSubRoute
  '/learn/task/$id': typeof LearnTaskIdRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/category/$slug/': typeof CategorySlugIndexRoute
  '/howto/$category/$sub/$tool': typeof HowtoCategorySubToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/prompts': typeof PromptsRoute
  '/ranking': typeof RankingRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/learn/scratch': typeof LearnScratchRoute
  '/learn/spin': typeof LearnSpinRoute
  '/learn/swipe': typeof LearnSwipeRoute
  '/tool/$slug': typeof ToolSlugRoute
  '/admin/learn-tasks': typeof AdminAdminLearnTasksRoute
  '/admin/prompts': typeof AdminAdminPromptsRoute
  '/admin/tools': typeof AdminAdminToolsRoute
  '/category/$slug/$sub': typeof CategorySlugSubRoute
  '/learn/task/$id': typeof LearnTaskIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/category/$slug': typeof CategorySlugIndexRoute
  '/howto/$category/$sub/$tool': typeof HowtoCategorySubToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/prompts': typeof PromptsRoute
  '/ranking': typeof RankingRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/learn/scratch': typeof LearnScratchRoute
  '/learn/spin': typeof LearnSpinRoute
  '/learn/swipe': typeof LearnSwipeRoute
  '/tool/$slug': typeof ToolSlugRoute
  '/_admin/admin/learn-tasks': typeof AdminAdminLearnTasksRoute
  '/_admin/admin/prompts': typeof AdminAdminPromptsRoute
  '/_admin/admin/tools': typeof AdminAdminToolsRoute
  '/category/$slug/$sub': typeof CategorySlugSubRoute
  '/learn/task/$id': typeof LearnTaskIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/category/$slug/': typeof CategorySlugIndexRoute
  '/howto/$category/$sub/$tool': typeof HowtoCategorySubToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/prompts'
    | '/ranking'
    | '/search'
    | '/sitemap.xml'
    | '/admin/login'
    | '/learn/scratch'
    | '/learn/spin'
    | '/learn/swipe'
    | '/tool/$slug'
    | '/admin/learn-tasks'
    | '/admin/prompts'
    | '/admin/tools'
    | '/category/$slug/$sub'
    | '/learn/task/$id'
    | '/admin/'
    | '/category/$slug/'
    | '/howto/$category/$sub/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/prompts'
    | '/ranking'
    | '/search'
    | '/sitemap.xml'
    | '/admin/login'
    | '/learn/scratch'
    | '/learn/spin'
    | '/learn/swipe'
    | '/tool/$slug'
    | '/admin/learn-tasks'
    | '/admin/prompts'
    | '/admin/tools'
    | '/category/$slug/$sub'
    | '/learn/task/$id'
    | '/admin'
    | '/category/$slug'
    | '/howto/$category/$sub/$tool'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/browse'
    | '/prompts'
    | '/ranking'
    | '/search'
    | '/sitemap.xml'
    | '/admin/login'
    | '/learn/scratch'
    | '/learn/spin'
    | '/learn/swipe'
    | '/tool/$slug'
    | '/_admin/admin/learn-tasks'
    | '/_admin/admin/prompts'
    | '/_admin/admin/tools'
    | '/category/$slug/$sub'
    | '/learn/task/$id'
    | '/_admin/admin/'
    | '/category/$slug/'
    | '/howto/$category/$sub/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  PromptsRoute: typeof PromptsRoute
  RankingRoute: typeof RankingRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  LearnScratchRoute: typeof LearnScratchRoute
  LearnSpinRoute: typeof LearnSpinRoute
  LearnSwipeRoute: typeof LearnSwipeRoute
  ToolSlugRoute: typeof ToolSlugRoute
  CategorySlugSubRoute: typeof CategorySlugSubRoute
  LearnTaskIdRoute: typeof LearnTaskIdRoute
  CategorySlugIndexRoute: typeof CategorySlugIndexRoute
  HowtoCategorySubToolRoute: typeof HowtoCategorySubToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/$slug': {
      id: '/tool/$slug'
      path: '/tool/$slug'
      fullPath: '/tool/$slug'
      preLoaderRoute: typeof ToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/swipe': {
      id: '/learn/swipe'
      path: '/learn/swipe'
      fullPath: '/learn/swipe'
      preLoaderRoute: typeof LearnSwipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/spin': {
      id: '/learn/spin'
      path: '/learn/spin'
      fullPath: '/learn/spin'
      preLoaderRoute: typeof LearnSpinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/scratch': {
      id: '/learn/scratch'
      path: '/learn/scratch'
      fullPath: '/learn/scratch'
      preLoaderRoute: typeof LearnScratchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug/': {
      id: '/category/$slug/'
      path: '/category/$slug'
      fullPath: '/category/$slug/'
      preLoaderRoute: typeof CategorySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/learn/task/$id': {
      id: '/learn/task/$id'
      path: '/learn/task/$id'
      fullPath: '/learn/task/$id'
      preLoaderRoute: typeof LearnTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug/$sub': {
      id: '/category/$slug/$sub'
      path: '/category/$slug/$sub'
      fullPath: '/category/$slug/$sub'
      preLoaderRoute: typeof CategorySlugSubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/tools': {
      id: '/_admin/admin/tools'
      path: '/admin/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminAdminToolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/prompts': {
      id: '/_admin/admin/prompts'
      path: '/admin/prompts'
      fullPath: '/admin/prompts'
      preLoaderRoute: typeof AdminAdminPromptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/learn-tasks': {
      id: '/_admin/admin/learn-tasks'
      path: '/admin/learn-tasks'
      fullPath: '/admin/learn-tasks'
      preLoaderRoute: typeof AdminAdminLearnTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/howto/$category/$sub/$tool': {
      id: '/howto/$category/$sub/$tool'
      path: '/howto/$category/$sub/$tool'
      fullPath: '/howto/$category/$sub/$tool'
      preLoaderRoute: typeof HowtoCategorySubToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdminLearnTasksRoute: typeof AdminAdminLearnTasksRoute
  AdminAdminPromptsRoute: typeof AdminAdminPromptsRoute
  AdminAdminToolsRoute: typeof AdminAdminToolsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminLearnTasksRoute: AdminAdminLearnTasksRoute,
  AdminAdminPromptsRoute: AdminAdminPromptsRoute,
  AdminAdminToolsRoute: AdminAdminToolsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BrowseRoute: BrowseRoute,
  PromptsRoute: PromptsRoute,
  RankingRoute: RankingRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  LearnScratchRoute: LearnScratchRoute,
  LearnSpinRoute: LearnSpinRoute,
  LearnSwipeRoute: LearnSwipeRoute,
  ToolSlugRoute: ToolSlugRoute,
  CategorySlugSubRoute: CategorySlugSubRoute,
  LearnTaskIdRoute: LearnTaskIdRoute,
  CategorySlugIndexRoute: CategorySlugIndexRoute,
  HowtoCategorySubToolRoute: HowtoCategorySubToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
