/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolSlugRouteImport } from './routes/tool.$slug'
import { Route as LearnSwipeRouteImport } from './routes/learn.swipe'
import { Route as LearnSpinRouteImport } from './routes/learn.spin'
import { Route as LearnScratchRouteImport } from './routes/learn.scratch'
import { Route as CategorySlugIndexRouteImport } from './routes/category.$slug.index'
import { Route as LearnTaskIdRouteImport } from './routes/learn.task.$id'
import { Route as CategorySlugSubRouteImport } from './routes/category.$slug.$sub'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolSlugRoute = ToolSlugRouteImport.update({
  id: '/tool/$slug',
  path: '/tool/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSwipeRoute = LearnSwipeRouteImport.update({
  id: '/learn/swipe',
  path: '/learn/swipe',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSpinRoute = LearnSpinRouteImport.update({
  id: '/learn/spin',
  path: '/learn/spin',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnScratchRoute = LearnScratchRouteImport.update({
  id: '/learn/scratch',
  path: '/learn/scratch',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugIndexRoute = CategorySlugIndexRouteImport.update({
  id: '/category/$slug/',
  path: '/category/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTaskIdRoute = LearnTaskIdRouteImport.update({
  id: '/learn/task/$id',
  path: '/learn/task/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugSubRoute = CategorySlugSubRouteImport.update({
  id: '/category/$slug/$sub',
  path: '/category/$slug/$sub',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/learn/scratch': typeof LearnScratchRoute
  '/learn/spin': typeof LearnSpinRoute
  '/learn/swipe': typeof LearnSwipeRoute
  '/tool/$slug': typeof ToolSlugRoute
  '/category/$slug/$sub': typeof CategorySlugSubRoute
  '/learn/task/$id': typeof LearnTaskIdRoute
  '/category/$slug/': typeof CategorySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/learn/scratch': typeof LearnScratchRoute
  '/learn/spin': typeof LearnSpinRoute
  '/learn/swipe': typeof LearnSwipeRoute
  '/tool/$slug': typeof ToolSlugRoute
  '/category/$slug/$sub': typeof CategorySlugSubRoute
  '/learn/task/$id': typeof LearnTaskIdRoute
  '/category/$slug': typeof CategorySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/learn/scratch': typeof LearnScratchRoute
  '/learn/spin': typeof LearnSpinRoute
  '/learn/swipe': typeof LearnSwipeRoute
  '/tool/$slug': typeof ToolSlugRoute
  '/category/$slug/$sub': typeof CategorySlugSubRoute
  '/learn/task/$id': typeof LearnTaskIdRoute
  '/category/$slug/': typeof CategorySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/search'
    | '/sitemap.xml'
    | '/learn/scratch'
    | '/learn/spin'
    | '/learn/swipe'
    | '/tool/$slug'
    | '/category/$slug/$sub'
    | '/learn/task/$id'
    | '/category/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/search'
    | '/sitemap.xml'
    | '/learn/scratch'
    | '/learn/spin'
    | '/learn/swipe'
    | '/tool/$slug'
    | '/category/$slug/$sub'
    | '/learn/task/$id'
    | '/category/$slug'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/search'
    | '/sitemap.xml'
    | '/learn/scratch'
    | '/learn/spin'
    | '/learn/swipe'
    | '/tool/$slug'
    | '/category/$slug/$sub'
    | '/learn/task/$id'
    | '/category/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LearnScratchRoute: typeof LearnScratchRoute
  LearnSpinRoute: typeof LearnSpinRoute
  LearnSwipeRoute: typeof LearnSwipeRoute
  ToolSlugRoute: typeof ToolSlugRoute
  CategorySlugSubRoute: typeof CategorySlugSubRoute
  LearnTaskIdRoute: typeof LearnTaskIdRoute
  CategorySlugIndexRoute: typeof CategorySlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/$slug': {
      id: '/tool/$slug'
      path: '/tool/$slug'
      fullPath: '/tool/$slug'
      preLoaderRoute: typeof ToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/swipe': {
      id: '/learn/swipe'
      path: '/learn/swipe'
      fullPath: '/learn/swipe'
      preLoaderRoute: typeof LearnSwipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/spin': {
      id: '/learn/spin'
      path: '/learn/spin'
      fullPath: '/learn/spin'
      preLoaderRoute: typeof LearnSpinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/scratch': {
      id: '/learn/scratch'
      path: '/learn/scratch'
      fullPath: '/learn/scratch'
      preLoaderRoute: typeof LearnScratchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug/': {
      id: '/category/$slug/'
      path: '/category/$slug'
      fullPath: '/category/$slug/'
      preLoaderRoute: typeof CategorySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/task/$id': {
      id: '/learn/task/$id'
      path: '/learn/task/$id'
      fullPath: '/learn/task/$id'
      preLoaderRoute: typeof LearnTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug/$sub': {
      id: '/category/$slug/$sub'
      path: '/category/$slug/$sub'
      fullPath: '/category/$slug/$sub'
      preLoaderRoute: typeof CategorySlugSubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LearnScratchRoute: LearnScratchRoute,
  LearnSpinRoute: LearnSpinRoute,
  LearnSwipeRoute: LearnSwipeRoute,
  ToolSlugRoute: ToolSlugRoute,
  CategorySlugSubRoute: CategorySlugSubRoute,
  LearnTaskIdRoute: LearnTaskIdRoute,
  CategorySlugIndexRoute: CategorySlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
