// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    // ── Development-only bypass ───────────────────────────────────────────
    // Enabled ONLY when NODE_ENV=development AND the request carries the
    // shared dev token. In production builds NODE_ENV !== 'development', so
    // this branch is never taken regardless of headers. The server returns
    // the service-role admin client so local writes succeed against RLS.
    if (process.env.NODE_ENV === 'development') {
      const devToken = request.headers.get('x-dev-admin-bypass');
      const expected = process.env.DEV_ADMIN_BYPASS_TOKEN || 'local-dev-bypass';
      if (devToken && devToken === expected) {
        const { supabaseAdmin } = await import('./client.server');
        // eslint-disable-next-line no-console
        console.warn('[auth] Dev bypass active — using service-role client for this request.');
        return next({
          context: {
            supabase: supabaseAdmin as any,
            userId: 'local-admin',
            claims: {
              sub: 'local-admin',
              email: request.headers.get('x-dev-admin-email') || 'admin@localhost',
              role: 'admin',
              app_metadata: { provider: 'dev-local' },
              email_verified: true,
            } as any,
          },
        });
      }
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }


    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
